# Generated by Django 5.1.3 on 2025-03-13 23:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoRask',
            new_name='ToDoTask',
        ),
    ]
